plugins {
    id 'java-library'
    id 'io.freefair.lombok' version '9.2.0'
}
java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}
repositories { mavenCentral() }
dependencies {
    implementation platform("io.fabric8:kubernetes-client-bom:7.5.2")
    testImplementation platform("org.junit:junit-bom:5.11.0")
    testImplementation platform("org.testcontainers:testcontainers-bom:1.20.4")

    testImplementation 'com.contentgrid.helm.integrationtesting:contentgrid-testcontainers-k3s-cilium:0.1.7'
    testImplementation 'com.contentgrid.helm.integrationtesting:contentgrid-junit-jupiter-k8s:0.1.7'
    testImplementation 'com.contentgrid.helm.integrationtesting:contentgrid-helm-client:0.1.7'

    testImplementation 'org.awaitility:awaitility:4.2.2'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'io.fabric8:kubernetes-junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.26.3'
    testImplementation 'org.testcontainers:testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:k3s'
    testImplementation 'com.rabbitmq:amqp-client:5.21.0'

    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.16'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test {
    useJUnitPlatform()
    environment('TESTCONTAINERS_HOST_OVERRIDE', '172.17.0.1')
    if (project.findProperty('disableDockerRegistryCache') ?: false) {
        systemProperty 'contentgrid.registryCache.disabled', 'true'
    }
}
