apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-rabbitmq.fullname" . }}
  labels:
    {{- include "helm-rabbitmq.labels" . | nindent 4 }}
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
  selector:
    {{- include "helm-rabbitmq.selectorLabels" . | nindent 4 }}
