{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-rabbitmq.serviceAccountName" . }}
  labels:
    {{- include "helm-rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm-rabbitmq.fullname" . }}-peer-discovery
  labels:
    {{- include "helm-rabbitmq.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm-rabbitmq.fullname" . }}
  labels:
    {{- include "helm-rabbitmq.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm-rabbitmq.fullname" . }}-peer-discovery
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-rabbitmq.serviceAccountName" . }}
